url: 'https://cedricg-mirror.github.io'
google_analytics: "G-KWXC4M8HVK"
theme: jekyll-theme-time-machine
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
